ci(PT13113): Add github workflow for code style
shopwareLabs/SwagPaymentPaypal pull request #16
Opened 2023-06-28 14:17 UTC by swDennis

2023-06-29 06:29 UTC, mitelg commented on .php-cs-fixer.cache
> +{"php":"8.1.2-1ubuntu2.11","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"blank_line_after_namespace":true,"class_definition":{"single
please add that to gitignore

2023-06-29 07:11 UTC, swDennis commented on .php-cs-fixer.cache
> +{"php":"8.1.2-1ubuntu2.11","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"blank_line_after_namespace":true,"class_definition":{"single
This is a draft.. it has long been done

2023-06-30 08:22 UTC, mitelg requested changes

2023-06-30 08:22 UTC, mitelg commented on .github/workflows/php-code-analysis.yml
> +        uses: rathmerdominik/docker-images-testing/.github/workflows/php-code-analysis.yml@sw-27107/fix-workflows-for-shopware-and-plugins
why not the official workflow?

2023-06-30 08:22 UTC, mitelg commented on .github/workflows/javascript-code-analysis.yml
> +    javascript-code-analysis:
this should be in the reusable workflow, see https://shopware.atlassian.net/browse/PT-13120

2023-06-30 09:02 UTC, rathmerdominik commented on .github/workflows/php-code-analysis.yml
> +        uses: rathmerdominik/docker-images-testing/.github/workflows/php-code-analysis.yml@sw-27107/fix-workflows-for-shopware-and-plugins
@swDennis  has to change this
This was for debug purposes and should never be used in production

It is imperative though that https://github.com/shopware5/docker-images-testing/pull/30 gets merged first **before** this gets merged

2023-06-30 09:02 UTC, rathmerdominik commented on Makefile
Nice one

this goes to @shopware5/shopware-core 
If you see any plugin without a Makefile include one at the next pull request with the basic commands
These provide a nice and easy to use standard

2023-07-13 05:48 UTC, mitelg approved these changes

2023-07-13 06:43 UTC, ennasus4sun approved these changes

2023-07-13 06:58 UTC, merged